#! /usr/bin/env bash

# Released into the Public Domain by tav <tav@espians.com>

# Halt on error.
set -e

readonly program="$(basename "${0}")"
readonly rundir="$(cd "$(dirname "${0}")" && pwd -P)"

# Check for dependencies.
depends_on() {
  readonly local all_deps=("${@}")
  local missing_deps=()

  for dep in "${all_deps[@]}"; do
    if ! command -v "${dep}" &>/dev/null; then
      missing_deps+=("${dep}")
    fi
  done

  if [[ "${#missing_deps[@]}" -gt 0 ]]; then
    tput setaf 1
    echo -e '\nThis script has unmet dependencies. You need to install these first:'
    printf '  %s\n' "${missing_deps[@]}"
    tput sgr0
    exit 1
  fi
}

depends_on convert gifsicle phantomjs

# Show instructions when using wrong arguments
if [[ -z "${1}" ]] || ! [[ "${1}" = 'https://asciinema.org/api/asciicasts/'* ]]; then
  echo "usage: ${program} <asciinema api url (of the form https://asciinema.org/api/asciicasts/XXXX)>"
  exit 1
fi

# Execute this in a subshell, changing to a temporary directory.
(
  readonly tempdir="$(mktemp -d -t asciinema2gif.XXX)"
  echo "Creating and changing to temporary dir: ${tempdir}"
  cd "${tempdir}"

  # rm -rf frames
  # rm -f asciicast.gif

  phantomjs "${rundir}/render.js" "${1}"

  echo '>> Generating GIF ...'
  convert -delay 5 -loop 0 frames/*.png gif:- | gifsicle --colors=256 --delay=6 --optimize=3 > asciicast.gif

  echo ">> Generated: ${PWD}/asciicast.gif"
)
