#! /usr/bin/env bash

# Released into the Public Domain by tav <tav@espians.com>

# Halt on error.
set -e

readonly rundir="$(cd "$(dirname "${0}")" && pwd -P)"

# Execute this in a subshell, changing to a temporary directory.
(
  readonly tempdir="$(mktemp -d -t asciinema2gif.XXX)"
  echo "Creating and changing to temporary dir: ${tempdir}"
  cd "${tempdir}"

  # rm -rf frames
  # rm -f asciicast.gif

  phantomjs "${rundir}/render.js" "${1}"

  echo '>> Generating GIF ...'
  convert -delay 5 -loop 0 frames/*.png gif:- | gifsicle --colors=256 --delay=6 --optimize=3 > asciicast.gif

  echo ">> Generated: ${PWD}/asciicast.gif"
)
